apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: externaldns
spec:
  encryptedData:
    password: AgCgt8UEmnfe+gUFFA78umP/S+ObqXboWME7VVDU0bpBoI1M7b3MEoDq+UgPwvDsd41j/QHrMsXBO9u9pmejECPG87tWzweHV7LZId7IaVqHLsHTA7NAK3saDHo/pK5mEsQi8aIjz9hZnNgChAuFKueQwcpqTowaHhaTKPV9RqXg4iLlH1VUBkBApneVpv9PEAuT51a4G2KnrS7bzSQarnQwaY9eLZTeyaJbn4K48vXnf5DTqazYSv+eQ+weACdavjmE86vB7lwiIK115wXsdH5z3uZn5K/NfSSzUXpMNLILYzdNODCGKhgBYTNCaJWDY95MN22zAoKmXNbZNAqhjiAsRap7TPbpY1RxHBkOmZYwEeXVD6AkKWYPmM10lx8wYxrECLYDsebgbW2gZEoIcQrkeWVPkdtKStcCvJwbzJ2HWJ0jLtl0FB5MopSe4rUuH1ltX2yGwP1T/DKQxPRyykyKjbGifQIWbq4bYlXt+7Z44dq/Ydh15CahBWKC+GsB8+meRcnnqMKf6oqEwXIdFiIExI7P6Lz0qbfiLuly8o1HCKCfDmDw987XFYjE46rNoNV1A7fk/jm7/iumh5SlsAia+jwevJF7YhzBpYCtJ6o6rPheUq0pboKWDjb4VKXcM0fn1eGxgzKiuL09dRUJlhFbkSSWV3xVc3r7ONrxpTPdcickrtovqwCNMAVVbaKEEV5cuKeyY11AE0eqs55yokSu/0qfYTnCZ+WQ+/vGFDh6Sx9sYUnWtpMnpE87X8kDsi3mMg==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: externaldns