apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: local-kirk
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
  crushRoot: kirk
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: local-picard
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
  crushRoot: picard
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: local-janeway
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
  crushRoot: janeway

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-local
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  # clusterID is the namespace where the rook cluster is running
  clusterID: rook-ceph
  # Ceph pool into which the RBD image shall be created
  #pool: local-kirk
  topologyConstrainedPools: |
    [
      {
        "poolName": "local-kirk",
        "domainSegments": [
          {
            "domainLabel": "hostname",
            "value": "kirk"
          }
        ]
      },
      {
        "poolName": "local-picard",
        "domainSegments": [
          {
            "domainLabel": "hostname",
            "value": "picard"
          }
        ]
      },
      {
        "poolName": "local-janeway",
        "domainSegments": [
          {
            "domainLabel": "hostname",
            "value": "janeway"
          }
        ]
      }
    ]

  encrypted: "true"
  encryptionKMSID: "user-secret-metadata"

  # (optional) mapOptions is a comma-separated list of map options.
  # For krbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
  # For nbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
  # mapOptions: lock_on_read,queue_depth=1024

  # (optional) unmapOptions is a comma-separated list of unmap options.
  # For krbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
  # For nbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
  # unmapOptions: force

  # RBD image format. Defaults to "2".
  imageFormat: "2"

  # RBD image features
  # Available for imageFormat: "2". Older releases of CSI RBD
  # support only the `layering` feature. The Linux kernel (KRBD) supports the
  # full complement of features as of 5.4
  # `layering` alone corresponds to Ceph's bitfield value of "2" ;
  # `layering` + `fast-diff` + `object-map` + `deep-flatten` + `exclusive-lock` together
  # correspond to Ceph's OR'd bitfield value of "63". Here we use
  # a symbolic, comma-separated format:
  # For 5.4 or later kernels:
  imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
  # For 5.3 or earlier kernels:
  #imageFeatures: layering

  # The secrets contain Ceph admin credentials.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

  # Specify the filesystem type of the volume. If not specified, csi-provisioner
  # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
  # in hyperconverged settings where the volume is mounted on the same node as the osds.
  csi.storage.k8s.io/fstype: ext4

# Delete the rbd volume when a PVC is deleted
reclaimPolicy: Delete

# Optional, if you want to add dynamic resize for PVC.
# For now only ext3, ext4, xfs resize support provided, like in Kubernetes itself.
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - discard
  # Need to add noload to be able to mount rwo readonly. See also https://init6.sh/posts/improving_cluster_backups_on_ceph_backed_clusters/
  # relevant Dmesg log:
  #[ 9072.923921] EXT4-fs (dm-10): INFO: recovery required on readonly filesystem
  #[ 9072.923946] EXT4-fs (dm-10): write access unavailable, cannot proceed (try mounting with noload)
  - noload