apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
  name: rook-ceph
  namespace: rook-ceph
spec:
  repo: https://charts.rook.io/release
  chart: rook-ceph
  version: v1.16.6
  targetNamespace: rook-ceph
  failurePolicy: abort
  createNamespace: false
  valuesContent: |
    csi:
      enableCSIEncryption: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-csi-kms-config
  namespace: rook-ceph
data:
  config.json: |-
    {
      "user-secret-metadata": {
        "encryptionKMSType": "metadata",
        "secretName": "storage-encryption-secret"
      }
    }
---
