apiVersion: v1
kind: Pod
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
spec:
      affinity: {}
      containers:
        - args:
            - "10000"
          command:
            - sleep
          env:
            - name: ROOK_NODE_NAME
              value: picard
            - name: ROOK_CLUSTER_ID
              value: 6d411027-be13-4142-9dea-d351911475f6
            - name: ROOK_CLUSTER_NAME
              value: rook-ceph
            - name: ROOK_PRIVATE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ROOK_PUBLIC_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              value: rook-ceph
            - name: ROOK_MON_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: data
                  name: rook-ceph-mon-endpoints
            - name: ROOK_CONFIG_DIR
              value: /var/lib/rook
            - name: ROOK_CEPH_CONFIG_OVERRIDE
              value: /etc/rook/config/override.conf
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: ROOK_CRUSHMAP_ROOT
              value: default
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: ceph-username
                  name: rook-ceph-mon
            - name: ROOK_FSID
              valueFrom:
                secretKeyRef:
                  key: fsid
                  name: rook-ceph-mon
            - name: ROOK_OSD_STORE_TYPE
              value: bluestore
            - name: ROOK_CRUSHMAP_HOSTNAME
              value: picard
            - name: CEPH_VOLUME_DEBUG
              value: "1"
            - name: CEPH_VOLUME_SKIP_RESTORECON
              value: "1"
            - name: DM_DISABLE_UDEV
              value: "1"
            - name: ROOK_OSDS_PER_DEVICE
              value: "1"
            - name: ROOK_LOG_LEVEL
              value: DEBUG
            - name: ROOK_DATA_DEVICES
              value: '[{"id":"/dev/disk/by-partuuid/ec18f5f2-676a-244b-9540-213b546d5cb3","storeConfig":{"osdsPerDevice":1}}]'
            - name: ROOK_CEPH_VERSION
              value: ceph version 19.2.1-0 squid
            - name: ROOK_OSD_CRUSH_DEVICE_CLASS
            - name: ROOK_OSD_CRUSH_INITIAL_WEIGHT
          envFrom:
            - configMapRef:
                name: rook-ceph-osd-env-override
                optional: true
          image: quay.io/ceph/ceph:v19.2.1
          imagePullPolicy: IfNotPresent
          name: provision
          resources: {}
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-data
            - mountPath: /etc/ceph
              name: ceph-conf-emptydir
            - mountPath: /run/ceph
              name: ceph-daemons-sock-dir
            - mountPath: /var/log/ceph
              name: rook-ceph-log
            - mountPath: /var/lib/ceph/crash
              name: rook-ceph-crash
            - mountPath: /dev
              name: devices
            - mountPath: /run/udev
              name: udev
            - mountPath: /rook
              name: rook-binaries
            - mountPath: /var/lib/rook-ceph-mon
              name: ceph-admin-secret
              readOnly: true
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - --archive
            - --force
            - --verbose
            - /usr/local/bin/rook
            - /rook
          command:
            - cp
          image: docker.io/rook/ceph:v1.16.6
          imagePullPolicy: IfNotPresent
          name: copy-bins
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /rook
              name: rook-binaries
      nodeSelector:
        kubernetes.io/hostname: picard
      priorityClassName: system-node-critical
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-ceph-osd
      serviceAccountName: rook-ceph-osd
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/lib/rook
            type: ""
          name: rook-data
        - emptyDir: {}
          name: ceph-conf-emptydir
        - hostPath:
            path: /var/lib/rook/exporter
            type: DirectoryOrCreate
          name: ceph-daemons-sock-dir
        - hostPath:
            path: /var/lib/rook/rook-ceph/log
            type: ""
          name: rook-ceph-log
        - hostPath:
            path: /var/lib/rook/rook-ceph/crash
            type: ""
          name: rook-ceph-crash
        - emptyDir: {}
          name: rook-binaries
        - hostPath:
            path: /run/udev
            type: ""
          name: udev
        - hostPath:
            path: /dev
            type: ""
          name: devices
        - name: ceph-admin-secret
          secret:
            defaultMode: 420
            items:
              - key: ceph-secret
                path: secret.keyring
            secretName: rook-ceph-mon
        - hostPath:
            path: /
            type: ""
          name: rootfs