apiVersion: batch/v1
kind: CronJob
metadata:
  name: freshclam
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: freshclam
    spec:
      template:
        spec:
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            fsGroup: 100
          containers:
            - image: clamav/clamav:1.5.1_base
              name: freshclam
              command:
                - freshclam
                - --on-update-execute=EXIT_0
              resources:
                requests:
                  memory: 2G
              volumeMounts:
                - mountPath: /var/lib/clamav
                  name: clam-db
              securityContext:
                runAsUser: 100
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
          volumes:
            - name: clam-db
              persistentVolumeClaim:
                claimName: clamdb-pvc
          restartPolicy: OnFailure
  schedule: '40 8 * * *'
