apiVersion: batch/v1
kind: CronJob
metadata:
  name: freshclam
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: freshclam
    spec:
      template:
        spec:
          containers:
            - image: clamav/clamav:1.4.2_base
              name: freshclam
              env:
                - name: CLAMAV_NO_CLAMD
                  value: "true"
              resources: {}
              volumeMounts:
                - mountPath: /var/lib/clamav
                  name: clam-db
              securityContext:
                runAsUser: 100
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
          volumes:
            - name: clam-db
              persistentVolumeClaim:
                claimName: clamdb-pvc
          restartPolicy: OnFailure
  schedule: '40 8 * * *'
