apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  labels:
    app.kubernetes.io/name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clamav
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clamav
    spec:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 100
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: clamav
          image: clamav/clamav:1.5.1_base
          securityContext:
            runAsUser: 100
            runAsGroup: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          resources:
            requests:
              memory: 2G
          command:
            - /init-unprivileged
          env:
            - name: CLAMAV_NO_FRESHCLAMD
              value: "true"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  echo 'PING' | nc 127.0.0.1 3310 | grep -i PONG
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  echo 'PING' | nc 127.0.0.1 3310 | grep -i PONG
          startupProbe:
            failureThreshold: 30
            periodSeconds: 10
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  echo 'PING' | nc 127.0.0.1 3310 | grep -i PONG
          ports:
            - containerPort: 3310
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: clam-db
      volumes:
        - name: clam-db
          persistentVolumeClaim:
            claimName: clamdb-pvc