apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamdb-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-insecure
  resources:
    requests:
      storage: 2Gi
