apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamdb-pvc
  labels:
    # Just virus db definitions. No need to backup
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 2Gi
