coredns:
  isClusterService: false
  serviceType: LoadBalancer
  service:
    loadBalancerIP: 192.168.2.92

  env:
    - name: ETCD_USERNAME
      value: root
    - name: ETCD_PASSWORD
      valueFrom:
        secretKeyRef:
          key: etcd-root-password
          name: etcd-password

  # Default zone is what Kubernetes recommends:
  # https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
  servers:
    - zones:
        - zone: .
      port: 53
      # -- expose the service on a different port
      # servicePort: 5353
      # If serviceType is nodePort you can specify nodePort here
      # nodePort: 30053
      # hostPort: 53
      plugins:
        - name: errors
        # Serves a /health endpoint on :8080, required for livenessProbe
        - name: health
          configBlock: |-
            lameduck 5s
        # Serves a /ready endpoint on :8181, required for readinessProbe
        - name: ready
        # Serves a /metrics endpoint on :9153, required for serviceMonitor
        - name: prometheus
          parameters: 0.0.0.0:9153
        - name: forward
          parameters: . /etc/resolv.conf
        - name: cache
          parameters: 30
        - name: loop
        - name: reload
        - name: loadbalance
        # Limit to local hostnames and don't fall through. This should prevent grabbing public dns entries.
        - name: etcd
          parameters: home.arpa felix-prasse.de
          configBlock: |-
            stubzones
            path /skydns
            endpoint http://10.43.142.0:2379
            credentials {$ETCD_USERNAME} {$ETCD_PASSWORD}
etcd:
  persistence:
    enabled: false
  # This job fails if the networking-etcd-jwt-token secret is not there yet?!
  preUpgradeJob:
    enabled: false

  replicaCount: 3

  auth:
    rbac:
      existingSecret: etcd-password
    token:
      enabled: false

  service:
    clusterIP: 10.43.142.0

