coredns:
  isClusterService: false
  serviceType: LoadBalancer
  service:
    loadBalancerIP: 192.168.2.92

etcd:
  persistence:
    enabled: false
  # This job fails if the networking-etcd-jwt-token secret is not there yet?!
  preUpgradeJob:
    enabled: false