---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: networking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-internal
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-internal
  template:
    metadata:
      labels:
        app: external-dns-internal
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.17.0
        args:
        - --source=service
        - --source=ingress
        - --provider=coredns
        env:
          - name: ETCD_URLS
            value: http://10.43.142.0:2379
          - name: ETCD_USERNAME
            value: root
          - name: ETCD_PASSWORD
            valueFrom:
              secretKeyRef:
                key: etcd-root-password
                name: etcd-password
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-public
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-public
  template:
    metadata:
      labels:
        app: external-dns-public
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.17.0
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=felix-prasse.de
            - --provider=cloudflare
            - --ingress-class=public-nginx
            - --source=ingress
            - --default-targets=dyndns.felix-prasse.de
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-key
                  key: apiKey
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
