gitea:
  strategy:
    # Just because currently we use ReadWriteOnce for data...
    type: Recreate

  redis-cluster:
    enabled: false
  redis:
    enabled: true
    master:
      persistence:
        existingClaim: gitea-redis-master-0

  # TODO
  # https://gitea.com/gitea/helm-gitea#external-database
  # Any external database listed in https://docs.gitea.com/installation/database-prep can be used instead of the built-in PostgreSQL.
  # In fact, it is highly recommended to use an external database to ensure a stable Gitea installation longterm.
  postgresql:
    enabled: true
    auth:
      enablePostgresUser: true
      username: gitea
      database: gitea
      existingSecret: postgres-users
    primary:
      persistence:
        existingClaim: gitea-db

  postgresql-ha:
    enabled: false

  persistence:
    enabled: true
    create: false
    claimName: gitea-shared-storage-v2

  service:
    ssh:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ssh.git.felix-prasse.de
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
      server:
        SSH_DOMAIN: ssh.git.felix-prasse.de

  ingress:
    enabled: true
    className: public-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "git.felix-prasse.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "git.felix-prasse.de"
        secretName: gitea-cert # < cert-manager will store the created certificate in this secret.