gitea:
  strategy:
    # Just because currently we use ReadWriteOnce for data...
    type: Recreate

  redis-cluster:
    enabled: false
  redis:
    enabled: true
    master:
      persistence:
        existingClaim: gitea-redis-master-0

  # TODO
  # https://gitea.com/gitea/helm-gitea#external-database
  # Any external database listed in https://docs.gitea.com/installation/database-prep can be used instead of the built-in PostgreSQL.
  # In fact, it is highly recommended to use an external database to ensure a stable Gitea installation longterm.
  postgresql:
    enabled: true
    auth:
      enablePostgresUser: true
      username: gitea
      database: gitea
      existingSecret: postgres-users
    primary:
      # Modify hba configuration to include replication. Required for pg_basebackup
      pgHbaConfiguration: |
        host     all             all             0.0.0.0/0               md5
        host     all             all             ::/0                    md5
        local    all             all                                     md5
        host     all             all        127.0.0.1/32                 md5
        host     all             all        ::1/128                      md5
        local   replication             postgres                         md5
      extraVolumeMounts:
      - mountPath: /backup
        name: backup-volume
      extraVolumes:
        - name: backup-volume
          emptyDir:
            sizeLimit: 500Mi
            # Since this database is very small we can live with this being in memory.
            medium: Memory
      podAnnotations:
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD pg_basebackup -D /backup/current -X fetch -U postgres --no-password"]'
        pre.hook.backup.velero.io/timeout: 120s
        post.hook.backup.velero.io/command: 'rm -R /backup/current'
      persistence:
        existingClaim: gitea-db

  postgresql-ha:
    enabled: false

  persistence:
    enabled: true
    create: false
    claimName: gitea-shared-storage-v2

  service:
    ssh:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ssh.git.felix-prasse.de
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    additionalConfigFromEnvs:
      - name: GITEA__DATABASE__HOST
        value: gitea-postgresql
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: postgres-users
            key: password
    config:
      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
      server:
        SSH_DOMAIN: ssh.git.felix-prasse.de

  ingress:
    enabled: true
    className: public-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "git.felix-prasse.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "git.felix-prasse.de"
        secretName: gitea-cert # < cert-manager will store the created certificate in this secret.