admin:
  password: AgADpqP9pogftKmcyKGd0EPUd7NRcnrTSw9pRiuRLV5onW0nZXFrgOsKk3iQI776k/kNMDLRgcLlIVTDhkKWVGVlV4eQlWq1bEqAHQIv0WWdN54n6+jm/RPl1FYGh6ozkTY0Ae8QCit0NF+atVAuodHPzN+gjMrU13L4MaeMr/Ody9DbX8p12OT6v0rje/YPQQ9J0wpAm16NRCjp4ehiu7s76a7OTtC2ma0tdXb+qzj+zMuezPJpOGBcX1yBdYovf1OnB777aNDCV6zB1dYNP5PUw9x/9rfSDQDQa0edq5LtTfvYtFBFN/ecHd1QPpjUENhHXsJjwueliJefKZN/0hLqKJE5vkU0aeskwZ2C+fBLMamHqOqGHm5J7vnEnD+RQzE1yJKXrfsaFdm5z/cak4AGEWlsVaqCR3kYMHFlqmeRqjI9NMi3mfq+yPN9Mg5ucf5DeHszXmtb/NG+Er6tPE9Hw0dzvjedNt8w3XrEybCFZQq+miXcQNRVzy/7Z4+LTgQEs9OaitPWpZyJ9OnfSCiHXpTuhM4J50J4LAlBFuvPByVbvxGrV7/16gaNObDii7c/M6iTRyfGEzkFO7VfBVBpxW8WYOoRHRmesC5Yi7lK3tFO5vz5BrmR9rGYWjZ5BALfAJcb34gENUAYgd7EtZvIvnHDRyJJ0zXeAOEf+PaIpkSPgXRsFveNgMpfK3PjWOk1fNmtSVBNIdGWXbnwIibu4sQa98vh4BJiRmpKqYM=
  username: AgAhOpS2a7PF3Dj8mH1V8CA5g1Ld5QqmzWi7XEYuOemJcrTBq+G6mJFjZ1mzCRK8EDnTIVGSlV636l78MLJNluYn3STClAFbD+hfJosP4/TJPD51d3U4XkrVtRHrq1vDeZuXjf+BY6fyfCh4utdCCisCueSfba1b0MKsCVrxs/XJClUr8mhitqHEsUJbWqhD7alyhlVyJ9xpTadqzwXmjH/Njh8dds0wc41CFZKf7UmchlwjWF2TvTBFP+3xfkWhUiBaNedCgFmBY5O3PSmdNn/hv4bdm9CWJ/nBZDtZGJf4Ix2+3Ssq88Myt0gEA3Z9xPEm/7Osv2nO+Ofowxr4SyrXB5usflI9DY80vnJYNhxuZ8Pxw39wOouQuwyvhGESKYeB6a5QMPjWMumqW1/AgVXdCWawvDYSDrolfVvSd6G7BdGdzpD0BQmLjjAlVvycmF/uB6D/Cj+25Co/fSBtaZtwreoae55WgveR3IRQodGWPzcx6noEddyO+dyvkGa9StlvuiIBikGo0TZX+gpUOXu65pvLwXOhebNlWyzvO/u5ALtnSL0N69e3DyuE7EZ+npCIKr006xEi1Yz5bZKO+kHGhmHKm8GFSqio0lZm+MwoZlOlid7Ok7WTdnOmr3H1TFAfkcZPtSYWhsYZkMpNO56yrArdBq2dOEQqs45lqOPPSyhJX4aGYpiCXAlJvVaPDi3CMRWS

bucketName: nil

valkey:
  podSecurityContext:
    fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false

gitea:
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
         drop:
           - ALL

  valkey-cluster:
    enabled: false
  valkey:
    enabled: false # Use own dependency because of bitnami
  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  persistence:
    enabled: true
    create: false
    claimName: gitea-shared-storage

  service:
    ssh:
      type: LoadBalancer
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    additionalConfigFromEnvs:
      - name: GITEA__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: host
      - name: GITEA__database__NAME
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: dbname
      - name: GITEA__database__USER
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: username
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: password
    config:
      queue:
        TYPE: redis
        CONN_STR: "redis://gitea-valkey.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&"

      session:
        PROVIDER: redis
        PROVIDER_CONFIG: "redis://gitea-valkey.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&"

      cache:
        ENABLED: true
        ADAPTER: redis
        HOST: "redis://gitea-valkey.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&"

      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
      server:
        SSH_DOMAIN: ssh.git.felix-prasse.de

