gitea:

  valkey-cluster:
    enabled: false
  valkey:
    enabled: false # Use own dependency because of bitnami
  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  persistence:
    enabled: true
    create: false
    claimName: gitea-shared-storage

  service:
    ssh:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ssh.git.felix-prasse.de
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    additionalConfigFromEnvs:
      - name: GITEA__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: host
      - name: GITEA__database__NAME
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: dbname
      - name: GITEA__database__USER
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: username
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: pg-gitea-app
            key: password
    config:
      queue:
        TYPE: redis
        CONN_STR: "redis://gitea-valkey.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&"

      session:
        PROVIDER: redis
        PROVIDER_CONFIG: "redis://gitea-valkey.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&"

      cache:
        ENABLED: true
        ADAPTER: redis
        HOST: "redis://gitea-valkey.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&"

      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
      server:
        SSH_DOMAIN: ssh.git.felix-prasse.de

  ingress:
    enabled: true
    className: public-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "git.felix-prasse.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "git.felix-prasse.de"
        secretName: gitea-cert # < cert-manager will store the created certificate in this secret.