apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-workflow
namespace: argo
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.7.6/install.yaml