apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.46.2
    helm:
      valuesObject:
        crds:
          full: true
        server:
          authModes:
            - server
          ingress:
            enabled: true
            hosts:
              - workflows.home.arpa
            ingressClassName: traefik-internal
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo