apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.23.2
    # Kubeseal expects the chart under the name sealed-secrets-controller and in namespace kube-system
    helm:
      valuesObject: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system