apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: descheduler
    repoURL: https://kubernetes-sigs.github.io/descheduler/
    targetRevision: 0.32.2
    # Kubeseal expects the chart under the name sealed-secrets-controller and in namespace kube-system
    helm:
      releaseName: descheduler
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system