apiVersion: v1
kind: Namespace
metadata:
  name: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: coredns
    repoURL: https://coredns.github.io/helm
    targetRevision: 1.39.1
    helm:
      releaseName: coredns
      valuesObject:
        isClusterService: false
        serviceType: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking