apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: gitea
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        bucketName: gitea-bkt-95187899-5958-4fb0-a6d0-dd3510efcb70
        gitea:
          service:
            ssh:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: ssh.git.felix-prasse.de
          ingress:
            enabled: true
            className: traefik-public
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: "git.felix-prasse.de"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - "git.felix-prasse.de"
                secretName: gitea-cert # < cert-manager will store the created certificate in this secret.
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
---