apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: gitea
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        gitea:
          ingress:
            enabled: true
            className: public-nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: "git.felix-prasse.de"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - "git.felix-prasse.de"
                secretName: gitea-cert # < cert-manager will store the created certificate in this secret.
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-internal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: gitea
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        admin:
          password: AgBp5I3Zi25pKRr5lb610jFrXVoMUjNdNUlMLnvrCpPpNLGNwKGONrdn74DHGq2J7BCyjDPpJOi/o36tN2GG+lbJL1v+l8Ou8ZIedcIxUaqZLTlR+uYkETAgQBMfsgAOAIvWMngZHFmo3Kktg++hodo0BM6pn+RjktXXscqtKEIZ0IW8TZ+UsBpM/cDZRCWoWcI5dqGcVf9tUQMH8AntDYeC6r8eR6hXF2R23m46p/UebDCrQiXR/j0g6vxgoNCmEnrWd8ETdI6FuOuAFFVdlOTSPeUBFVFnmoHalpGjSh3y/etUiFm5qDzSqHP2VsRSeGN9QuDFl9OKQ0LYHv/U96kaG8B0LpW8tOaIeduYgHdpFZNjJMg4iJupWXu8AzW01M7vg/n7bXXf0jsfI5hg3krhCQkdZJUjR5kOCHiAZcsGdIEfqXtC7FUxq2kC5BxViJY1a5Z8Ky67hNII64YzAKP9Ikr7HNVMd5GPY4OM//p+0uSYKpGlLuTo5PGL5DoWVf7IK3/g7Ii3GBgSqavJLuDCh4wI1USUygFu9iI2PCD5aUIYaN2SuBGmr0skQ+Nh1xJB6Hov2J4DbU4KGMlISs7JHVX6opG9ObvLrW4dFqeJCbqkBCfUZHewioZDjJEY1bmNXngERMMyrLYSXQokoa5SgSZ6z3aFCcTEqwFawzRY76ekAK2RWGSGB89iV31KM+zZz4vF3K9rxdGKuu+rCsH1M+XqIg==
          username: AgCepnSf4niqpHEhAErYMVAyKQreFgVh5KsIro30yGZA29GCJTKJmYsuP7SBJK1ECNSqpPKGhilj4bsBhfp7ppAeUaUwD/C191hNwHYpbFAiEgceuyeRGXTJFFRp2itKJjJ5rH91Ie9GDkgHyYDs5DvsIpoVvtlD+4tjCxBPh7m80acQXIFZNgqY/OWybLfTQ8cSQs/Hd1NZz6yY8/oXBxEym0+X57Lo+XVbpRiPn+lxWlZo1CLx+LTxpBboNe3oWw4T4/Zc2RkE2Sxg0DiEKZon6ebiKNBNPr+xMDW1zNHxxh1b5oQ+ipWd3JFKbaR9PzDNOCI1wfnv+kVVyzlz63GL4Ayujh8Wi3Ni+c+4dgy2S+XCWCKOOn/ZPYHO+Hw0TEhvGEM6Qdm1LO+Mq41piNxElkbcEuhxW2hK43cEFgAMI2WR/MgJ9UWPh1kEzSnSET4zEkWO9PEyVmHeDita/RK+rmEjBZIClb9qBDd0hINcqrOSDfP0QQ5VgkTpEScfnnPaC0fbexnfZRRj8FZgYw6E7SB6EU1LtpSIz8IQAOQtvniKEI0x+vm7a6M58iQQP6wvnxoDuO8FNJ0XnPzW/biKYdT/omNb8izDqT+6bCersJRqeS+CSyaK8ooQLD2f0EV7ouotS10j7uom7nZzcfpAjQWeLVHEEbX0lEGZVeV2JZSB0cMBQHIzuAP9ZFKN00GUiH/X

        gitea:
          service:
            ssh:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: ssh.git.home.arpa
          ingress:
            enabled: true
            className: internal-nginx
            hosts:
              - host: "git.home.arpa"
                paths:
                  - path: /
                    pathType: Prefix
          gitea:
            config:
              server:
                SSH_DOMAIN: ssh.git.home.arpa

  destination:
    server: "https://kubernetes.default.svc"
    namespace: internal