apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    loki_user: AgBMq4sh7iCbAmBX/DN/u+C4e+fCJtQ5CFLHorX16SUNpIMVBLG8Kc8AdeeZ4onTUh/4iE0CRWGx57x/vvCf5qOiZy3wThj7UhMxuGeKSwPM3wLoTDiJ5HXmD7lJlQZQxkoO0U6UNfP8bRHZy+URryAyOyOjrNg/ln/qyMURD43oe2E48Pj8LkhbGMIgRhWFzpuq4EQFYOabm98cK+rJaOI2qFkmO3thqxsrtJDmyTZK78cByw+r7AZAOu68cpzYo9uAmBGylEdeVMHFNuqpv9iD8mRpc8dQH4ALMBahf3b+TVD9ovLz9VzBWX3OQHces+s7aqtiGbl1qTW6onCVTeGzhPGzYjOKBVT+ZtFw2dnFV2ALaGHQmmtjdIdxPMHVwg/dg7s312Y+BRohR71/REuJpU0qCFfUrmf4Sj3bwpOddu8LDaai6aN/2cUFtlIZuGtKw+UUsfaoT+1xhOqwvzY7vpN9fDl1n9yw0MDr6hzTMgRro1hSSdIJu+wFzJ0tuYIrlrQQgUQvWvUFRHXyYShoaTSesaT1d2VjJ5cMBtfw/qAtLPMFGGXHe7lZcNIm+UEpxzPmQwdb7pPRq9g+s2NJg8i/nqZMeB/pjip8JCaryLpgNJZe6Ks1Nll7KJd7KPU4Z1R+2KDMbf5gh25a/94LRt1hrTLvffzPEf6ODaFYMaSTD9YxMzbSLlwHs4azrIfZM626N3Jq
    prometheus_user: AgAdYeawxKpLLyl9ln0/IdjNTqlEIRMSLptYv8FI4SyyzOVNko3t2DLylfoOgsc4EWWrOxWT92nrUW7mu4oyX1mgyMR6wnw7mUe1WNm1GwdVESeL0kYiWaNG/Mi2/GQ7XnZVczj0rrt0dMQ6uQRbM0JX7++ZBGfM90NX20LdrI9yCujZUoQSG/9dO4wHBWYYaMo713xmGxojVwTx4isMZkWvcDy5jXvzD5gS+Ezt/Yf65txpYBEY75UfYxndNRnpqUWIoACuyiACHzrWY105a/TnMZIgNg7vxov9CizZDVJw/XYX5/IcT/2Yi7f8usmWPh1fqcxrc4E6bzjfoIPY5BGE1/3Hezp8xjgrl1DlnHXkbIFP+R/XdcTx6yX0Dql3Ik5YVi/Uwx3qlCd+w/XH5L97XTerpXaeBDhOzmEMXB2puaobbWZBHMjitebjEu6SAVryPyfouWerdH0L0v4M/LSG8be9pJ2Rw2qmntWIWSAHdVoAwH1+6t8cejonmGVD0al1F0P+GyrnL6Uc8Ur/jyDlE3EHG4n5PE9649p1MtO+PJr0ZVNFjmMwHaM30aFZFBzq1rlgnFiFFVGju2XU0CemGLgx93XWS9zr6PLz8ZtHqbO8v1A1RFd0V659CyoRa1/i3Dw88K5XTYrk1LB/HW+mmtb2HSlzmEPxYu2Zuxj8rVyoOLtodo8wfLzBeYS5jhhTZmW8qIVn
    token: AgAiZmrgPIkEsO03w5UiQ9OCr4/CWkIILSt8bPxBdNvYmVUHX1SBotUQxyyVCXwiIddGwfrVGQEMCRIF+2NFt3adEEDPrbCf7Oxzdwa5PX/Gxb8oaWN1Xe/Pm/thV1JpjvUNR+IssmXWtXJ4DIauZGE//oAiPrg+NTLNNVu3MMHjmux4ZhG5M8pAIhfnIvyXRDTs3mQ6zpR4KjAdJ3penVsi9nKdvs9Z2fTyjJuTrDUrxihJ0GGtRHRZUU4NpYk+ohs2DyXM2SAJkdHCRfu3ire+PZFl+syGbKlQ58wdSEHrWZE+WCAczJjnvceSlxY4DBmaDqsNfBrjMYTSTjXCTw9315HOyqD96KdH1uAwxWQCoBo3n8TuS5JjQugoiFDVjA19iElYuvilwR/+NoI5Xj3Az5SBRaZMIjywZ3AJ6EBK3slqClknRVSKlmX4p5KfgJa6jRwMeH6jAgMsnlHetrzYktTGDpQfyTkX/8x/4p5YwjFswt7EBhNONgd8Fq4GDp1Pafch3v1zngG954mAYperhf8C13cEcFXkpti+KXM7qH6HyywGkVGf9JNDGICyR4bBDMnYs/ey7uyYse4l8V3rIM9wMsA73vIQ9u/J2pHjDf0Na+Wbs8rtpuY+YNojnrtrZIVat5+g8YdL6/P8fa8qfRoHQ1Gs7F9VWPge5MVIG8gxlQ9QlYDqiIhyROeSBv1h8o1UUYIF5XYiFJSbVXMBuID4tZoFOAcQu2IBbnx+zbietERV/qpfwuwZIc2z2fnYdg5vSDuCSTRnYlOG0XOe9Se3HMzl5uqCr41wDV4LOf4O35geTbA3QCuLy0a68O1nw30UHYwOs0asXzeIzv45YEyeEbWfpS7ihSt44dZ36nnAdc8K/8/D1MpMsiI5kSQxZwFfIFUwpLfJTXk=
    traces_user: AgCRPk0rh+rOHjwJzRekCGcGNp/gUEiEDeGJDvyfoix6tkDW79fl+W5SDsHLzkDc/+1/JXzO0PKqoacL+vtLy0QqlGsweN7qT75BFE8dZqGu/cP7LfkUvUcBeMNmIuNE6sGYqG7I3ExVF3h6JvIx/PVXXBg0MD/4DNZLEiZ17/kcpvZFFKc6Os2Y3Kv1cq92klK4O0Fqgy24YZR1q4vkAtI5wKsEprMfbECXCJQ6ReNUJuVjlebqiD69nk7z4vAsB+3GF5rp1cCYGt89/mTmhkJZhoQrTA3CHIGUV0DZ7iYlPgaKQbd1jr7Uc6UMEOaApIsGfVfCHNMziCE1j9XF8G0PsSDqBPW79qKRR5kRgK41unJH7WEx+hQUNlvsVQvz6BHXx4cFaTlHyAHtS3woZpXcNx4YgqSjWYPCZKlFFtlIkzpYAHvSNTjxTmYOWoGSOqgm62s8MHJ++pqs3scUbnjn2zdjtCAMzPDrq7Vz7hpJa+pisM04mr+LfZRQmSPm/4wYXKR0r1mSCKqJiD4YEKJrJU10+iaON1czFpqo7fat9Pra2Gbl3X215Af2CYCIlBKPQgQVh2IWIEaJszbLJR2cL1f/afRHp8yne96C3dAJSJqg3lCoOQbXvhRgwwhXbPApYTtHX5+4kaW93r6L4uJcO5qRDbo6JZKvKJdLCXXK9sxXikif/PCKobus2cLv2La/VUZH8Rlm
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.0.23
    # Kubeseal expects the chart under the name sealed-secrets-controller and in namespace kube-system
    helm:
      releaseName: grafana-k8s-monitoring
      valuesObject:
        cluster:
          name: k3s-nue
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
            auth:
              type: basic
              usernameKey: prometheus_user
              passwordKey: token
            secret:
              create: false
              name: grafana
              namespace: monitoring
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-012.grafana.net/loki/api/v1/push
            auth:
              type: basic
              usernameKey: loki_user
              passwordKey: token
            secret:
              create: false
              name: grafana
              namespace: monitoring
          - name: grafana-cloud-traces
            type: otlp
            url: https://tempo-prod-10-prod-eu-west-2.grafana.net:443
            protocol: grpc
            auth:
              type: basic
              usernameKey: traces_user
              passwordKey: token
            secret:
              create: false
              name: grafana
              namespace: monitoring
            metrics:
              enabled: false
            logs:
              enabled: false
            traces:
              enabled: true
        clusterMetrics:
          enabled: true
          opencost:
            enabled: true
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: k3s-nue
              prometheus:
                username_key: prometheus_user
                password_key: token
                existingSecretName: grafana
                external:
                  url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom
          kepler:
            enabled: true
        prometheusOperatorObjects:
          enabled: true
        clusterEvents:
          enabled: true
        nodeLogs:
          enabled: true
        podLogs:
          enabled: true
        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
        autoInstrumentation:
          enabled: true
        integrations:
          alloy:
            instances:
              - name: alloy
                labelSelectors:
                  app.kubernetes.io/name:
                    - alloy-metrics
                    - alloy-singleton
                    - alloy-logs
                    - alloy-receiver
        alloy-metrics:
          enabled: true
        alloy-singleton:
          enabled: true
        alloy-logs:
          enabled: true
        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring