apiVersion: v1
kind: Namespace
metadata:
  name: jdownloader
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-encryption-secret
  namespace: jdownloader
spec:
  encryptedData:
    encryptionPassphrase: AgADW4ZcYLcU6F8ksoZCV6FLUpeFAUq9Fa9r3rAyuuIWNA1g6+E5ZOgMsdQ3HHnmLJNq9vmm8GmxHoTsPe2rFNKGWhDpXRwviLYQBarLp/+uAwF1kJ35dG/QZd4/Q6DIjSJGCv1dD8KCKJOD+zZllgEldfHDY0vs5VPS4SNYWuEaJKMfO/XckHKOpv5ZlhliKguJFCJmO3hYqxxEY931pVPL6I2tiL8AbeYzXzoD6RMbfNDi93NHfxXxRarRhd4HktTq1u+/1RB77yXJNXDEHzpzACUFEKdFG8fnXqCotqOIbJmSIyUwwotqZFXwVvkxeba9po5lBrI/R1/2wCLtSSbF6LDmFGg234VjOSDc31lxtKsEEcrQFiwosJ0oE+B3cQBjhjCHWSuhrMPTLjridnzFoV00/VMA5oPE+1gE54MkpC+YyS00FU1x7Bi73JdSyvFDc3bgc7f1rV46aPjmebkr3yRXuZntl+lLD/8aox1RiiNjirZAwjBcGL8i3f9OpBushaLGxy34wev8kn57pR+qE8p0Btqov74gPMbtCCVazZhaTpairL0itvBnihXprxky+3+LGV3hbEhqK23ok8YzUyAPmAWyqNYFLu+LG1Ub2VuzLdi9fdRorufsl2PdSmay0T1DwNxrO8m7URTyIVCq/rNFdOMabOrWKrLFyGcrza+AlzLfM5h/Y9dGteM8/QkWggQUjPoFNcHYgjSxwzt099pyAgh+QbUAJj45UeOePeko8tBmgphj7xx2152XBYElDw==
  template:
    metadata:
      creationTimestamp: null
      name: storage-encryption-secret
      namespace: jdownloader
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: downloads
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jdownloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: jdownloader2
    repoURL: https://pmoscode-helm.github.io/jdownloader2/
    targetRevision: 1.2.1
    # Kubeseal expects the chart under the name sealed-secrets-controller and in namespace kube-system
    helm:
      releaseName: jdownloader
      valuesObject:
        persistence:
          enabled: true
          storageClass: rook-ceph-block
          size: 20Gi
        additionalVolumes:
          - name: downloads
            persistentVolumeClaim:
              claimName: downloads
        additionalVolumeMounts:
          - mountPath: /downloads
            name: downloads
        ingress:
          enabled: true
          className: internal-nginx
          hosts:
            - host: "downloader.home.arpa"
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jdownloader