# TODO https://github.com/minio/operator/blob/master/docs/cert-manager.md#create-operator-ca-tls-tenant-1-secret
# Idea is to use https://cert-manager.io/docs/trust/trust-manager/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  sources:
    - repoURL: https://github.com/minio/operator
      path: .
      targetRevision: v7.0.1
      kustomize:
        namespace: minio-operator
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: minio-operator
                namespace: minio-operator
              spec:
                template:
                  spec:
                    containers:
                      - name: minio-operator
                        env:
                          - name: OPERATOR_STS_AUTO_TLS_ENABLED
                            value: "off"
                          - name: OPERATOR_STS_ENABLED
                            value: "on"
                        volumeMounts:
                          - mountPath: /tmp/certs
                            name: tls-certificates
                    volumes:
                      - name: tls-certificates
                        projected:
                          defaultMode: 420
                          sources:
                            - configMap:
                                items:
                                  - key: root-certs.pem
                                    path: CAs/custom-public.pem
                                name: internal-ca
    - path: minio-operator
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio-operator

---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
---
# Disable for now. Need to figure out how to do this without killing my network during backups.
# Currently this is very inefficient: longhorn-backup/velero data mover -> ingress -> minio -> nfs -> zfs pool
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: minio-tenant
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#  sources:
#    - path: minio-tenant
#      repoURL: {{ .Values.spec.source.repoURL }}
#      targetRevision: {{ .Values.spec.source.targetRevision }}
#  destination:
#    server: "https://kubernetes.default.svc"
#    namespace: minio-tenant