apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
  source:
    path: nextcloud
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        bucket: nextcloud-bkt-4f8bfd8a-f59a-4a8e-86cc-0095f4421ad1
        nextcloud:
          ingress:
            className: traefik-public
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
              - hosts:
                  - cloud.felix-prasse.de
                secretName: nextcloud-cert # < cert-manager will store the created certificate in this secret.
          nextcloud:
            host: "cloud.felix-prasse.de"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-internal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: nextcloud
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - value: nextcloud-bkt-16f3ce3d-5d88-473d-9205-2ef45e3792ba
          name: "bucket"
        - name: "nextcloud.ingress.className"
          value: "traefik-internal"
        - name: "nextcloud.nextcloud.host"
          value: "cloud.internal.home.arpa"
        - name: "postgres.version"
          value: "18"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: internal