apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 4.5.8
    helm:
      releaseName: nextcloud
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
          tls:
            - hosts:
                - cloud.felix-prasse.de
              secretName: nextcloud-cert # < cert-manager will store the created certificate in this secret.
        nextcloud:
          host: "cloud.felix-prasse.de"
        internalDatabase:
          enabled: false
        mariadb:
          # TODO Set password for db
          # TODO Configure storage properly
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud