apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.27.0
    helm:
      releaseName: sealed-secrets
      valuesObject:
        virtualHost: pihole.home.arpa
        dnsmasq:
          customDnsEntries:
            - address=/demo/192.168.2.103
        persistentVolumeClaim:
          enabled: false
        serviceWeb:
          type: LoadBalancer
          loadBalancerIP: 192.168.2.92
          annotations:
            external-dns.alpha.kubernetes.io/hostname: pihole.home.arpa.
          http:
            port: 80
        serviceDns:
          type: LoadBalancer
          loadBalancerIP: 192.168.2.92
        serviceDhcp:
          enabled: false
        ftl:
          FTLCONF_LOCAL_IPV4: 192.168.2.92
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole