---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-repo
  namespace: argocd
spec:
  encryptedData:
    password: AgCw7nNWXOWBcX+kjzWy/Cwte2+EVjxNaxCpcb//8Oemzn4Tt5m3j28PI8aqk2wZuiXWGmH+UQ+T9mSxAnpRC3E7GMlIGbBbF2C8fKUDsZVLuyydL7yoZjE5WvvcgQndY67hHra7Le0BvIrnPK4uJVLMk10xU44QQ26/tepfR9onIPCoZmg0H5gwNRX4nyUgvl/R023ywUIodGdk1zl3Rayxc9+R1MnubhR+vB1nwR3D9wgnmgZR48jNiGJCLdDbv+mLEhd9SE6usZYZNjZJHZmiwHQGs4BkQyrH5TnVSYR3N3w3r5RHFVmxR+5++CdGM8OIeBaWLHlgd9CdzxA/RVztDXt3n31hFkbSCvWpUm5cb7Q31IxC5bnQqedO3j/YPfldFiELT+Q4Codqo8EFqm8QpXtynDhBuJ687MkIHjSvOZthll1vRrllPq1vpzRN/4N2lRlZvQGHVnH3KMwu192+zazlJsHrgjMShH3E5L5ZTcXcyE432c3q/VTMll1ZYuOunyD2VTBJkRC7jYCJnII8kVcH/WjiGl+RWr/USfk9Mdn8lPKgc+Vd25lAFlNEk/6mel4rdQHkZRSjHItWw1Khakfg8smC+LtDnhj+8dR/T51yJUAxW1KWTPejVAlHIsYnuKTIVW1+3NrLvAldRCXmSPRGu1yvwn22C8mHCCVPp3YMBcTamzylxejsbm+q4yJ9VIeKDpkdNVBrX1iHOL463P8CtJNojwFiTow0u1A0Ie+IjcYPTTT7AQZtwHjLEXJ4Nzy/NPZAIDV5inH/+zPp8TU/thlHFYjt2bo2awg37HI+B39C8qX6vZ11TyU=
    project: AgBslYkhOBtIKL7oP/UtIfb8lGAfPH8Fciy/nf7mN/6tK1sb+1XzsVL8An+WWCyuB0apbJ9mt8XgkfFzvhq/LnzztP+0IjTcIARnzobsJG4pwEPNOhR2NWSSErALVDfk8eVxkASpdx9hRftcURpIYgc15y8aDj4udAqGkpsu961IA4ppUbEJRlUk0h18evRx6FwgBC4i9CnsMLFesNPbeSAucCSXRyJ/JjhpLiKiVKNMKl0tseVAW71w4bMMs4r736jYsf+Xjgjz+Di3J/aSKeEUOlXA7CljD/jc58/906ay4zl7GTWj4sgbDE+XXSf89runXLLJc0qcwCt/cD+HG5qHs9ZWAS4QMIc1OB3QvKMDcBBBqN+Flb86cUSoGFY0dWROyLLaSb9F/7xtvbIvkO8Evj7uy54TC3jaS+oxT5b/5isCl1Em2vQN2i3y7BVyJt0WRDqB1sDaVmxrnESu4bogV1PJn1+TdDJfWP/7NjKv18x8NckNKDk7A8fbUL40N7Gh32ICG5IWAxu+ltKdzG+sxJYkOmBu04oJ7Du4E0yMq0Qzlfr18CoDqFQPY78Nt6uL8CHMikOIQkfCbfL7r1Xi2pWomMQTBgnrvCh7cXvMIZQT1lpJaMP15Q0OqQPkSVftJ8o6E0ievpAzzuvIAa05tOeydLQx/jNbP8G6c8gbghWyBjFOBW0dSVR2omk3GvRMqgUbV3LM
    type: AgAWTk0uobQg0r5GhGCPsc9WYngljGQ9xcRURSCyOgd9FBkOXhr/OMAYeAWXQLVeVAcNH9vh1jlhU0QXUSFkz18i0ui/0+b+G/wOnUSDD/sgBzt9xAtRkEanE90h5Xi4ma0xx+IepcikhzL/1XvrexxemFBDbukiighEL6KnIj1WxUtFy2N+hlKemy/2wRPUGwfg5uFmdhxLQ7xSu27aUha8204A0Qdt2P/U5Z/ldxgGzxZKWZ/99gaEGduD/59+7QmqiZU7NB/CtSzS0L/G2xqQZRMRbtSq1l1HwGDneNUBZrwk4YipJb9c06SD0sz0dWPB7qIwTqSHOyZTgz1Tfez6IYZmY+I6LcSlzemx+pU2f6pl9oY23eO8bCxUov1kiANVVvu0RWvN+NF7xF1SPD2VKDeANpSzcgdLncMzYDxg43H5ucFrap5Vav0+xqSquoWKb+1qnNyS+dY6ZgFwpzu9RNA+I0CDbw3s9Z4IU1SyECWe1u9DOcKDkDY1SqgdlkwqaaCG9l2R+hn62nxGO6Zb8hBfa25s0j8UQF+jpSOJ2G7qZ07LNJSbzH/RJ2d/ICcr0gcZi5G7jSFLUlJZbtEF1gnE1fOU9tgWhSVagUql23n/qEghFlgVut//X4mus2HwmxV0Fx6F9eC0sJPVcAdXK4H6ruoyJUoaTCItXQ3XSQEo2qtshXO1ZuVLPcBk368FWSs=
    url: AgAnsG3EXeTz2JWssCrGhSNfqzQHfBjNocdsgnNvsUib+cMWPrt4M6hrDd5nHqDZJCsVVUgm4806485W+W6uTPCn3bhmOTUWopM9wQgfjbbAY2eLk1SkCgC2wm7IWBTYVWOuA64NsuS6B4LqJhzs0AMchpXr51BUUR4s2DeYH1tkYttOubovwbxfv7YkA7LhaYVMnQrlXyKfibPflBE5GkQclqu0QechIzQZA2cSFGs6cFOE/QA8cOzW7GTVYNtsQttz2HufCsRE+T+qex5p66NMV2edzb6r6mvfjFpLIXKKVeWjj9KRxRYLfQxQYs6+dvU7q866q/h4wfU30OM1sUudbE7bEKiu1p9mku/vBMjVDj6L+oxN1xMJwMGv748Wr0+cdYwRgiD9fYYXiChBH5MMTvpoD8ev4a944+tM96a7I97HzCQTCwp3gJvalLoBLrEkMyfCcCWEkRFiaQty+2hISH/ttAXZ35D+5p94C0P3Pg9DpvDFMRNAUD2R1VuySfcoNju/4OjWwliosKwWqFHFl2RWKvoV2ZM1BMsgrqydP9NJjcK87hfLfLhz0WlPXeu94yhbKVVr+5ZYSRRiFKRzvNUZ3Ru6g/kPXIAzuwEMfGDtprCzHrRvdcWFTGn8P+aF89CZMG47vnWMmKmILZOPy0nZOVRulehqtQVwOYVtq6usT2JUTlU/3EqQo41z6YaDKpLh9JCiJW/g+31baQXGS/1FdNFQrpcI83nTmyihzXWT8D88bThmLpyETo6fOg==
    username: AgCbWszIqwykMhpFunymoTxcv5kOrT23JmCYuO8tmW4SUeBxfes8r7UCAuXwL0Zc7w9Mnv576VTjTZDnUoGIHFevjXuZ0bKh8cK+8iSAjnvRaRYoZEYowOzS+b9KA0cT3PEzPdSgtggPXJ8QQyIVVopuryN6O2q1dB2Ii8XYHeeHv2b9GCIEjJlP22FF2n/qv8secL9phrP9FxIWv4ntufWWurrw57h+vu80+WuJYxHDUmnQXnSVixzF8l8sScztfRltg+eT3Mn6D2oyks5D2TdPh/xExxzlXEFsdDfZQ9ft47bxCU5XI6mTKLBlFtMLMlIfXrYqWj0vU0k+O4cCS5vyTKqUSM9XHWwd2fMLjN/HYJ9gEiRrA9iS5E3BpuLTA2hSaLOznf/gRpNYutTzQ60hxffqL2yV6PrZd6ASpomt/4rYwpBDziThxbN4+BptsBbJZR59wlkwSQIlbjjHjzDFtlrr5vgVYTVpyf8VDYnNPOesIcULULcmow7SjX0tYHSfZ2VltHTn2xlXQE+EiyUb45+DXHgQ3VGOjDSUMkAUrPZuaq+mipMqQWldQ/hlNJzEA8XJSOGP2Zn49jGMVKlZnjzzA/iNCOqKGswl8Snq2Ubsfa33KaarI/wlGcDseMknOvf2mPYu22b8b8gK6f+X0FLFpVmSxWs3sze/K1+PjdMwtQvbC8e0KEnWqsiihA/iuU37
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: private-repo
      namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: apps
    repoURL: https://github.com/flx5/argocd-apps-private.git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd