apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: false
      prune: false
  source:
    path: rook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph