apiVersion: v1
kind: Namespace
metadata:
  name: velero
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: credentials-velero
  namespace: velero
spec:
  encryptedData:
    cloud: AgBi83ELjaPPI0bADqtEdod22P37GVlqs4eViWMZIrUISE7lE0RzDtqcQEO48V+PNWJTSx3PgKvPRXMpYgEJQbA/9OLZQ+PzcxsLzp5XKjecr2Mgio1FtehP9IbDjits3j/ZzHZ8Bzm7/TtkK3wqZ91bvjnaLuYmmneq8jDl7hp6/vC7aroqcqtZ4COSpwRpL7oPBCOYH+Ishe/BRiSeuSgxbuX+jK6Touoen04KksdR9HQkpyEF/sFrNN7QkNOGqb8tr34aIKkoMxGK2nroCt8g674YZrKSC4+GcHhNdjqu6GStlq6NeAufN1pPgGfcHzgiy2IJiVmf9/TWOt9BA2QU0ZfMNvz1ge/ziTypkRK5iwC1WNduOdvi35g3NulYE+WCpYNyx0mYWUJmQfFSWCb6nidLPZJwmfvAesi8dRq6tFFs6lnNoom7hrexvlf9r92bfQCMLncEFXj4SnMlnlaUOKJamcztZwW3rTZn8DLy2yDWd88NC8V+IEQGOjTDSIqEfZzi2hFtBtKKEUeOryJ4TpqkDmMBxQTk17KUWK2VnCECFLSRH0dcAu7ewIwT+y+y9GqFjL2Msk8uKw/tighaMKOOROmZWFxPHa0qRh55dCKfuhBLnTpOxIJ/v4f68KnWP/l37eXztgC6T06uqffxiw+GDGxEPQTE8Zw8u5GRDdiss7+fbZercq7EJ3fsIYWrworNfiCABzX8Ejd2WdaZiBoNlyxVPb64iwV8xuGmAF4zR1FSQnSRHxpdgRhJ4U8IN5bMg3J9/MkWrazVokePD28j3P/aztJhBbRTm5FP0/AodrkB
  template:
    metadata:
      name: credentials-velero
      namespace: velero
---
kind: ConfigMap
metadata:
  name: node-agent-config
  namespace: velero
apiVersion: v1
data:
  packuppvc.json: |
    {
      "backupPVC": {
        "rook-ceph-block": {
          "storageClass": "rook-ceph-block",
          "readOnly": true,
          "spcNoRelabeling": true
        },
        "rook-cephfs": {
          "storageClass": "rook-cephfs",
          "readOnly": true,
          "spcNoRelabeling": true
        },
        "rook-cephfs-insecure": {
          "storageClass": "rook-cephfs-insecure",
          "readOnly": true,
          "spcNoRelabeling": true
        }
      },
      "podResources": {
        "cpuRequest": "10m",
        "cpuLimit": "1000m",
        "memoryRequest": "512Mi",
        "memoryLimit": "4Gi"
      },
      "loadAffinity": [
        {
          "nodeSelector": {
            "matchExpressions": [
              {
                "key": "kubernetes.io/hostname",
                "values": [
                  "nas"
                ],
                "operator": "In"
              }
            ]
          }
        }
      ]
    }
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-encryption-secret
  namespace: velero
spec:
  encryptedData:
    encryptionPassphrase: AgBu2NBB0s76QipO/nCIf+MjfzMmfxW4f75MJtXV6oZMDODDujsezLssL6wislcudFA+ZAlL5gJHxVMbI9KSwL8maOcl96y1a0gkfA19FUD26OcDTgv+61O/wy7DO6WEeZMAN/HjgzMR9bOdo4tfH7cRPm4Ld2HI7hR7LdHBAJ0tpNysQwr5t7GBIhRGHtEXzv7YhHTAIixDoMARMjf9PxZbmnUgpNQ4tT9qio0RRQxMpif6JYPGIlghcrjxm7pOOQfmuJDl0Nb9YWVyyihMV9Pve/W3GVMX4S/sJ3a5TaK93E/JG4gb2+vYSZX4pAl0mg/JcTho3+vT1GGl7MhoHFy7kLNt2yAGln7eEJ+EwYCQa2F+/ElIGTe36f4XSPlrGGBslDObKBJN0W11yukQUV0b0xbpKPA9OS7X5n2BavRqYUHGyyJdlh7zXr0gFUC+DzyxPvQbjlcEVzaOjWBqhC5GKpBamEgdRPvTP0S36jS1kTsIrb4uZfderWHx82wXtHmtLx576r2JHWcIpGxzHdwSDD4175Bg0nsaH+EjH3n0Cmdg/UldCosnvGNN3tmlQe43PkkBv5QioITo4k7RE3RNcd0gMs8kfAC2EDFGuRIpRqsw5PzKJaBnuMX6tvyFFhqGhNLM2ai/JRBLPQWh8hSCi/sluSbi+m6RK0F9zkX281fcdAI3bDyigA+GW5OHHfONpfKsU7uY+2Mky9KP9CslGN6GjQRNiSB7K8HwJ9mxWa3a239ebJPVmMdBMSCEpEyPKA==
  template:
    metadata:
      creationTimestamp: null
      name: storage-encryption-secret
      namespace: velero
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgAcEqEEvM04dQxCta3U8wiUoD1XIvKbXlNzdgQ2zYxNzMm01aNxuaBLxZt12DoviWNAJ0MI8E5DkOIi1cvVfGmEL4FrlwJw8bdejJYhjOb9WS/doGuhCuGIQYY/OK5yVzGZ1vdbnXQ5PXuuuk5iXonHIVuWRri8aunhVMenvs799sE+w8pkwVEI3rsP5X/LjBy+8ASito3F5ixiX/7vSGVkuq2oxzMV7Qu6ngkxzod5g5H0GQAtEclsCB88VGrrdOzK8Y273wAry8C9RoGTrOaAM42bZFBsr32lo0rX22HccEhjH5lEasRHPOKoV/bCVvuQ1eLdbr9BNeEIO5ADaykisFxXpfY5c0ISb9Xfgz/VDFWHOjJF8ajdiXUtin3pPHb1qpX140dRh5YG4tU1a8BEIIbbSOO1WG1QzGHXp7soCU4kpHtMLKEoR3KVrtaaS/eAztOLZBxBK9lMUpHrYiW2MU9Qbju/UsHov2I0zlOW5Xu6MgNhGyuKtkBUMpK4K8CTGgNYqmo4Z6PaXmr051v+Decs9TENSxf6+O5ui8xplQx2Y2A9Cx27lDyo/D6jYlDAXgBgHw1WZ7SGUEyxoGGKtsi8tdfiK5zD/pljIH2jGxmWHBtZ1R8KJ6unbv227mYtZeCWhVKrniHgKgQ7xhb1+OKkk7It9/f0W4PSbw4vpl4fphKAt+b/Y3zDfWCMApdpVRi3Sua70ihceDDcZmZC
  template:
    metadata:
      creationTimestamp: null
      name: velero-repo-credentials
      namespace: velero
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 8.7.1
    helm:
      namespace: velero
      valuesObject:
        deployNodeAgent: true
        nodeAgent:
          # See https://init6.sh/posts/improving_cluster_backups_on_ceph_backed_clusters/
          extraArgs:
            [ "--node-agent-configmap=node-agent-config" ]
        credentials:
          existingSecret: credentials-velero
        configuration:
          uploaderType: kopia
          features: EnableCSI
          defaultSnapshotMoveData: true
          defaultBackupStorageLocation: minio
          #defaultVolumeSnapshotLocations: minio
          backupStorageLocation:
            - name: minio
              provider: aws
              bucket: velero
              config:
                region: minio
                s3ForcePathStyle: true
                s3Url: https://s3.nue.felix-prasse.de
          volumeSnapshotLocation:
            - name: csi
              provider: csi
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.2.1
            volumeMounts:
              - mountPath: /target
                name: plugins

  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero