apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBbyiAdaiUiYLJs3fMOwGPcnfuOdzLc1EmvhXm9PRDC7ONbxVkzw1lAFaw8p8a/SMUVdTi708LEjR9uV+65PV4tqsOhbqTLOKUmRrtwMauvFkwyZ6qUWW6527BdCMZH8CIat6PyNmB19weV+gz7OqWVkviUMULdCOHo6QHzl6M5Yga7Un4zJot7AsSHUq79ie9AlLi+CpZVsFLGd0LEnZpXEDYWOKosyocXHdSF8jYaYs5d6DrLRiZojidw/9feKn9w1erNNQjhh9KtxjdHDFRv/5+s1zcWop3wAtzDArj8t8tiSe4UfZj3wo6iqu+/67EufoQxy6C/CUWfPIZJqxjCxVSRDXH3rR9yoqlQapOGvAWcEN53kfy669OQNXIEdPLk+giUcFRU+CirJRUaIIrTok0dZnob8rkVkh1TPBuwtTbPYiC7MQeECuyD7ZAnxG4HbK7/WgIGnAI5eOiahHvK83WDor4X0AVzN9X7YF8OFGbB8jK4xpPBVsQ9avO2Qi4zOnNv4J/g7Z+Wc3kCIOX2tZOaXQd12iS/MHESuWoYsw1Y3dWRD0igNvuAowP3H+asGz0VDGlVxXI6kuUBQNmnBZhDJd/WaCIAnMyS42rVST8T+jjsm+Oj2V3V2RPtRKof8E+UICo0ts6yuHXr9SU+sLG6/o2CC+y2LgXn2lPfLf/GkJH2rOEsRmTPUhuvcEewtyjpGwxnb1Ekn6sAIHvZu77ITStw8gBGNl4l0Jho81bZwKA/pBnZ
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
