apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-immich-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-standard-bookworm
  instances: 3
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - CREATE EXTENSION IF NOT EXISTS vector;
  storage:
    storageClass: local-path
    size: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
type: kubernetes.io/basic-auth
stringData:
  username: immich # required field for kubernetes.io/basic-auth
  password: DktoH2jrLatjQtah # required field for kubernetes.io/basic-auth
