---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    password: AgAWbgW6ZyK52GqYKibU2b1YT+hmZWV3WFB7OUxYCkvAtxkydKmdvx9zrbgtvOpt+MS/eJi6mL0GjsTFIwSq7uNv/DAsca0/9kL13SHMVGnlRpZVdw0sqHfzckSjhArfGVRu4PgBwrwtI01EmCF1XE+GMA50eW18atOMj0uiscgtbEaag6upetwvemquEA9P+oczS9salkV2jzGgR0b8LiAeFb0mxj3Qu+0SuL+bJ7T+lnQqbpAM6dVgcXnEqKJUBVj/eNQYWmhdPEVaqy9g2VH2okgJDfEajAkqMU7iDj5X6h4KVZQZD8vZ59dp7VWUaZwrv1ta8pmkKizErA1qa+Q264r21GUtk5UK2c+tonZaJ0U3Pf1vHPDHVPM9qFx0ufnQJsMItDzAHOh2/Fx3gFe+TlMcE2BOfvBMvQokxvvLrtZQGXdiRKdk7eECeLHgKrHYiIG6STAvjHjK1eOrQGWyy86wpALJrRYxZ7/4T/9GSglggoKfSHYsRTeakamB5LMI0o59/o3F0cAKC42T9A0I0HuFB42KOlDZZ/7qMRpVI+47bnQRQ5+cBrBb+j8j1zYb9xNIhLXz5eZpROxD48C3GwLqMozAbL3y8FdAzTccNvxZS36DlJe6/a/3QcejIKRshr35VwqO218x784cJch8BfhSNNli45Fn6dGEiNXJf/y1CgTH5jN+yPANYtYHoI0DLCK9Yze5XdmskKCrKzJaAyFPWsi0iakn4mslHe3XNYnk4fAV96WMlvK2/6fDbovT9w==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: pihole