apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-grafana
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  storage:
    storageClass: local-path
    size: 4Gi  # Never change this. local-path does not support resizing!