---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA6HeX8pcAIOCoP967Fe8SlYZWCoX+88DDDJQOMiB78P6t/MkUegMEorQFOlLn4KjcW5RoRIRQHhXIPJ/k67yuAJgGYgaACKmO52q+EVAELefpCq7c/w6ugx94HuoZfUEJTU2gb3CHJ28n/YoU0xvnUUuqpq1KXmK2zPiEzlAO7OfKiN+5LqJ0AjNaqZTkxFslhIaMK2Bm9fdc7lYUQ2zOBMPleGQAQIejEwE/rQCxyWE1i9lC5KiR8KOJfnJ99s76TqqGR+wg6bshySqaM4U/LzqNAxWvdLKyIVPx/Y/dfbheykTBzQduZAbuNQhdtpxbUqGRCgIwc1CfkgJ4dcGn1XYshEGfEQ0RHmBqlkilAgcdzW/aFsTg/k1AD0eq5ECwZBb3kZxFaput3wv3R6Q0/8nVmk85QMW/lxl39CkoMouRlqYYFrqKpJqFfvOzhcRh6dVRykPs1TT/sFIho8KMmachT4uezFQcZLZSLZGHpXHEWJuCwIUhQMx1Uag8VuMjkM1Oq7Kt7XpXqkEwqAJP7lJ4ZrlQ0rFcaSFMKBNbr6Ph/hdVVhuut1meOMlBhqsCE50VxOrtQx9whyTYqx7gq8NWn5TO10FC/uAemfbtIGdynXZ1zfvLFcvElAGBbJ9jZ2zEryQvVcZUXf4cTz5mpQpM/tI0tj+3w0pdL/rYN6xinMu1g3r9f+WAuMYs/5qCNkC/eih4cPir+IlGmaufZyLl2YewzWogxUJnqjf6v+/T1j5jIrijC
    admin-user: AgBhIinosGS91fqvpTMUgdpmJGR8wxvZ9yolWmUBpeYyhmbvTuUXoQRCuWl2LjKVx9GwFfAPT1ldn0W2AIoCEh34oUMMvif+XyGV7JAHm5ef6z7TBHM4TdFI4PKh7gx8pOvODzl1F8KXvPMkBDi5jEvESoeOTbhRCiNlwN2W8GK6vD5qyP1iF+PW9xxgdNM+DyhNBF0mD6ocgEm8wfBPrykbPp+Jr42hJ+qE+OsQN82LB5+xHKYsFyDM+uuVTDF7sAzOal84iFYSc3fxhxITWhf27MvsER7a42eCVHSEzcgX2HTyDXgRUJn/DWegkOhY6cy+w33E5pCMlrk8C6eMclgIgaOxOJbZoWJr0i6tmUwGDB/dHgxTzxEgk0Q/y40u6lrJa7VVVm8PqCgWqtjxyJKMgyhztdqXDJcIZjwjMb2hgwMzniYVHbzWUTmuMa3ct+U1GUmd2bHHGGTvn4J+6zEeDFtqShbt7d3/wmTCdLEOyzRbHoRthG9Djhm9r30SNo5hV5t31jW6r7DGfVDMkkqzm6QHCZ9WC6ZFwwHyVLJYWHDIQpifrs8HWSnMz9l7v8f1DY+T4v1gCwhtz/ql6VvqvKHMhkXMVLSUh5LOhFMpZyyo4NehuNRcsScPkFaM9REJOVrDVnHM+a0f7XKOtWhTkeAsiFw/IgdLJRXf5yh/yTLhoJKJo3fxhn9dkgL1mjEcMO2nKQ==
  template:
    metadata:
      name: monitoring-grafana
      namespace: monitoring
    type: Opaque