apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  labels:
    app.kubernetes.io/name: calibre-web
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre-web
    spec:
      serviceAccountName: default
      containers:
        - name: calibre-web
          image: "ghcr.io/linuxserver/calibre-web:0.6.24"
          imagePullPolicy: IfNotPresent
          env:
            - name: PGID
              value: "568"
            - name: PUID
              value: "568"
            - name: TZ
              value: UTC
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          volumeMounts:
            - name: books
              mountPath: /books
            - name: config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: books
        - name: config
          persistentVolumeClaim:
            claimName: config