apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-nextcloud
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
  bootstrap:
    pg_basebackup:
      database: nextcloud
      owner: nextcloud
      source: postgres-cluster
  storage:
    storageClass: local-path
    size: 4Gi  # Never change this. local-path does not support resizing!
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ceph-store
  externalClusters:
    - name: postgres-cluster
      connectionParameters:
        host: postgres-cluster-rw
        user: streaming_replica
        sslmode: verify-full
      sslKey:
        name: postgres-cluster-replication
        key: tls.key
      sslCert:
        name: postgres-cluster-replication
        key: tls.crt
      sslRootCert:
        name: postgres-cluster-ca
        key: ca.crt
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket
spec:
  generateBucketName: nextcloud-bkt
  storageClassName: rook-ceph-bucket
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ceph-store
spec:
  configuration:
    destinationPath: s3://nextcloud-bkt-4f8bfd8a-f59a-4a8e-86cc-0095f4421ad1/
    endpointURL: http://rook-ceph-rgw-my-store.rook-ceph.svc
    s3Credentials:
      accessKeyId:
        name: ceph-bucket
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: ceph-bucket
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
  retentionPolicy: "30d"