apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: pvc-1fbec63f-9f13-4224-b91a-c7a439a4045d
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    nodePublishSecretRef:
      name: longhorn-crypto
      namespace: longhorn-system
    nodeStageSecretRef:
      name: longhorn-crypto
      namespace: longhorn-system
    volumeAttributes:
      diskSelector: ssd
      encrypted: "true"
      nodeSelector: ""
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
    volumeHandle: pvc-1fbec63f-9f13-4224-b91a-c7a439a4045d
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-ssd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    longhorn.io/volume-scheduling-error: ""
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
  name: pvc-c2d7a7c4-b7f6-4158-9821-537b619bf718
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    nodePublishSecretRef:
      name: longhorn-crypto
      namespace: longhorn-system
    nodeStageSecretRef:
      name: longhorn-crypto
      namespace: longhorn-system
    volumeAttributes:
      diskSelector: boot
      encrypted: "true"
      nodeSelector: ""
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880"
    volumeHandle: pvc-c2d7a7c4-b7f6-4158-9821-537b619bf718
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-ssd
  volumeMode: Filesystem