apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: nextcloud-nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: longhorn-ssd
  volumeMode: Filesystem
  volumeName: pvc-1fbec63f-9f13-4224-b91a-c7a439a4045d

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: nextcloud-nextcloud
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-ssd
  volumeMode: Filesystem
  volumeName: pvc-c2d7a7c4-b7f6-4158-9821-537b619bf718
