apiVersion: v1
kind: ConfigMap
metadata:
  name: modsecurity-nextcloud-config
data:
  nextcloud-rule-exclusions-config.conf: |
    # Generic rule to disable the plugin
    #
    # Plugins are enabled by default.
    #
    # They become active by placing them in the plugin folder. It is possible to
    # control plugin activation via setting a variable. This can be done in the
    # plugin config file here.
    #
    # The predefined variable name is meant to be "<plugin name>-plugin_enabled".
    # For the nextcloud-rule-exclusions-plugin, this means it can be disabled by setting
    # tx.nextcloud-rule-exclusions-plugin_enabled=0.
    #
    # Note that a global setting of this variable overrides the setting here.
    # That means the "enabled" variable is only set by this rule if it has not
    # been set before.
    #
    # Feel free to set the variable unconditionally here by replacing the
    # SecRule line with an unconditional SecAction statement.
    #
    # SecRule &TX:nextcloud-rule-exclusions-plugin_enabled "@eq 0" \
    #     "id:9508010,\
    #     phase:1,\
    #     pass,\
    #     nolog,\
    #     ver:'nextcloud-rule-exclusions-plugin/1.5.0',\
    #     setvar:'tx.nextcloud-rule-exclusions-plugin_enabled=0'"
    
    # https://help.nextcloud.com/t/modsecurity-apache-nextcloud/83987/9
    SecRule &TX:nextcloud-rule-exclusions-plugin_enabled "@eq 0" \
         "id:9508010,\
         phase:1,\
         pass,\
         nolog,\
         ver:'nextcloud-rule-exclusions-plugin/1.5.0',\
         chain"
         SecRule REQUEST_HEADERS:Host "!@cloud.felix-prasse.de" \
            "t:none,\
            setvar:'tx.nextcloud-rule-exclusions-plugin_enabled=0'"