apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-encryption-secret
  namespace: gitea
spec:
  encryptedData:
    encryptionPassphrase: AgBovczbolw+++Sc6JGLmoTXJhg/lnXknvgBzWhlVswExNCIqwA7lzPTw9bC8x0WhGOdir5/O0HkAHxT5LUINELhLRb9jvidGj8q7lnF4Jg9aEGr2zRN2lPcIz9G8mvA30qcxWyBj0UOn/QLANprmDI2bB7I7XDYWbGLIUnLiK08jLUhCUy7pcPRaxRLxIQSk5dSo3RRajT6mpGenuyZgRhCPpHbMKD9sZej79PnewNbG0W7jYMj5xviUOHcWWx1+w0G2urjtOiNsaFbQqTt0N1BLiMOCg00rU/P68XaoplNSfhUt433/9vBJwC3H8pJEidducCxoGEMZp3MPyRl+MLwWcX26kAXkucmoQFscYjV6wvthH8/nznyTmRgyJ460x+uFZ+92k+QorXAVXD3jc17PSLCdeZRrmCd6lXBn4hhEtfZbTRnRQJBHvkJmBUd3jJF6nu8vfjEux9L38rRMtYJqwJFOuwTtf+Zd9o/9AkJZUyQxWSTk2nGhBHQxCOK+XzBzYexeW7FL65vD7WdRLjZpBWRRk0A391+MP4g1wEBlidL8HETdjNE6YsnQUkEZXgYOA3CtrNh47kCgO0YO2O3FGZXcgXUow9HVxlXn7z91x3Pdsg6Fr8WCgr3Syp2fohRwUTMuWPwt2IZLkMCqq53HCERwS3Q+8+iEl7JtOjBD2++zAZIr3k+A+JvLSOYbVsyC3aNVr2GdiCM0YZPLgGBcI6SKuMh3nv6pbHysoa7y7N0jXxYthcoOlMZE8oW5gp9aw==
  template:
    metadata:
      creationTimestamp: null
      name: storage-encryption-secret
      namespace: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: gitea-shared-storage-v2
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: gitea-shared-storage
  namespace: gitea
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: gitea-db
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: gitea-db-dump
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: gitea-redis-master-0
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-ceph-block