---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgADpqP9pogftKmcyKGd0EPUd7NRcnrTSw9pRiuRLV5onW0nZXFrgOsKk3iQI776k/kNMDLRgcLlIVTDhkKWVGVlV4eQlWq1bEqAHQIv0WWdN54n6+jm/RPl1FYGh6ozkTY0Ae8QCit0NF+atVAuodHPzN+gjMrU13L4MaeMr/Ody9DbX8p12OT6v0rje/YPQQ9J0wpAm16NRCjp4ehiu7s76a7OTtC2ma0tdXb+qzj+zMuezPJpOGBcX1yBdYovf1OnB777aNDCV6zB1dYNP5PUw9x/9rfSDQDQa0edq5LtTfvYtFBFN/ecHd1QPpjUENhHXsJjwueliJefKZN/0hLqKJE5vkU0aeskwZ2C+fBLMamHqOqGHm5J7vnEnD+RQzE1yJKXrfsaFdm5z/cak4AGEWlsVaqCR3kYMHFlqmeRqjI9NMi3mfq+yPN9Mg5ucf5DeHszXmtb/NG+Er6tPE9Hw0dzvjedNt8w3XrEybCFZQq+miXcQNRVzy/7Z4+LTgQEs9OaitPWpZyJ9OnfSCiHXpTuhM4J50J4LAlBFuvPByVbvxGrV7/16gaNObDii7c/M6iTRyfGEzkFO7VfBVBpxW8WYOoRHRmesC5Yi7lK3tFO5vz5BrmR9rGYWjZ5BALfAJcb34gENUAYgd7EtZvIvnHDRyJJ0zXeAOEf+PaIpkSPgXRsFveNgMpfK3PjWOk1fNmtSVBNIdGWXbnwIibu4sQa98vh4BJiRmpKqYM=
    username: AgAhOpS2a7PF3Dj8mH1V8CA5g1Ld5QqmzWi7XEYuOemJcrTBq+G6mJFjZ1mzCRK8EDnTIVGSlV636l78MLJNluYn3STClAFbD+hfJosP4/TJPD51d3U4XkrVtRHrq1vDeZuXjf+BY6fyfCh4utdCCisCueSfba1b0MKsCVrxs/XJClUr8mhitqHEsUJbWqhD7alyhlVyJ9xpTadqzwXmjH/Njh8dds0wc41CFZKf7UmchlwjWF2TvTBFP+3xfkWhUiBaNedCgFmBY5O3PSmdNn/hv4bdm9CWJ/nBZDtZGJf4Ix2+3Ssq88Myt0gEA3Z9xPEm/7Osv2nO+Ofowxr4SyrXB5usflI9DY80vnJYNhxuZ8Pxw39wOouQuwyvhGESKYeB6a5QMPjWMumqW1/AgVXdCWawvDYSDrolfVvSd6G7BdGdzpD0BQmLjjAlVvycmF/uB6D/Cj+25Co/fSBtaZtwreoae55WgveR3IRQodGWPzcx6noEddyO+dyvkGa9StlvuiIBikGo0TZX+gpUOXu65pvLwXOhebNlWyzvO/u5ALtnSL0N69e3DyuE7EZ+npCIKr006xEi1Yz5bZKO+kHGhmHKm8GFSqio0lZm+MwoZlOlid7Ok7WTdnOmr3H1TFAfkcZPtSYWhsYZkMpNO56yrArdBq2dOEQqs45lqOPPSyhJX4aGYpiCXAlJvVaPDi3CMRWS
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-users
  namespace: gitea
spec:
  encryptedData:
    password: AgAS/KLVjw9vufV5nkso/34pxXyr85/TQW7PnB3t3qhKuDOuXNgH3mKuOcgvrjI6bODezl7rwHbd5ZDnlVSK00RQCDcSTi1aXffLXB6s1EUHOsGjxK61HON6b0ZQ7ku43RipK4zPZQLzrEiQHLmyl0B1MsoGMHzpeZXx32MqwHeizFHeM6YzGkOeFbOg/0cA8kakpppV+hJWLvBS3/V6CV70I3zq1VAqmRMO7rJhg4QOyUbo6JE8TnbZsGtOPixvljWQ45R969w+PeZChBac+RrE13+fcK3mCEXvRIlHT7g6uV6TrCJYoJ2yBCymT7qPEVL+DFQBtCM00ndc0QCjp9wAfKifZaIz6I+0RPQG2QI4XSkOW8KmD5+jqztoyASzj4rjmne6UeVMtiYkAhhH4PqmplqVUN40mqgqOGNGrZJCZGpbENOQeMdMiJ9bd8pA58M3ngpZzL2m0g+S1Cl0Y0sS32uBO7AcGrotJ389T6a8obFSwz9iM/E3fZTGnVWzW6niXhObUP48pXEtbcNXlflgAnJd2MSSrIx0soJslWRajjm4p4CMN16caBTuaO9IagVWGMT03OlNO60SSx+a7QJt0XvkSwK88hIwY8nb5ZTnUFu97OHMz1KQAJ6diJlhpqLbvLKqRv3ewjauF6byr0fR9ObKAr3nfGo70m3kLp6VeUZIhsk2EGd42Fh/Eu7w4C1OoJ28PiBaA/rZEd0Agb7g
    postgres-password: AgBoxkTXBr4DOeV32WbOFv0EaVhNB4Vsbp0XRFz9hfz5VlFTWwuhlGkf3sx6BcGY/q5YrkZM56OgNUcRPup8Es+bmZr3usALEmoxnEkEZT2p5o9SayPa+G9MZx5LcRlxJuD6xe0+sHE9banfq+dTjEXRc1ABsegDq+GM/lOMMnRrLmS7q7A4c0oAReKgHZQqRDV4jEGirfcL3UHw0XPbl2lIGpbmO74i40GmJdbvWJYB96M5rTK2CbJUcXyez8WAU0puaQLznOToiOJBFte7PH6lUboTcBtxmc750Thp3Oz2KLVvrgQS0rGvZ1l6ykIuDEqrNrDla5ASj0mb5946VNaFRfElGB9gARKZStdRAp6CqUwYeO+Vp8IeXnVfM23Ypm8BI6Sh6ZJNGdmP9HByqm3xfxb6duAj8NV17Cy26O/60HfcdLbmRSPl/L9pOYSyQA/nLIbmDo3XoGpJQgHEpJzQT6XsNQKCCb2CKTLZLANxegq+f/ixqoR6HoqQ6cLPfxIHgs/M7nW+3qUfq9gzy87k4Tm/yPWYMUEeEkNpSpoPSTHbCqBdCXAJCCZbpVK0T9x8XbqfYbdqdBpj2/3UMR2PMvaIxkK9G+crs8sIwiiD4lVb0Lqian1jHXHzNpbyIWMbGCwBnbT7jS6ExQ6Yn6DPwIEtohxJGviYhQ15/JyKHVaCSYTWfAWCunmhm76wXGv2uq5cw9gaiPnQOu1/Ge8t
  template:
    metadata:
      creationTimestamp: null
      name: postgres-users
      namespace: gitea