---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgADpqP9pogftKmcyKGd0EPUd7NRcnrTSw9pRiuRLV5onW0nZXFrgOsKk3iQI776k/kNMDLRgcLlIVTDhkKWVGVlV4eQlWq1bEqAHQIv0WWdN54n6+jm/RPl1FYGh6ozkTY0Ae8QCit0NF+atVAuodHPzN+gjMrU13L4MaeMr/Ody9DbX8p12OT6v0rje/YPQQ9J0wpAm16NRCjp4ehiu7s76a7OTtC2ma0tdXb+qzj+zMuezPJpOGBcX1yBdYovf1OnB777aNDCV6zB1dYNP5PUw9x/9rfSDQDQa0edq5LtTfvYtFBFN/ecHd1QPpjUENhHXsJjwueliJefKZN/0hLqKJE5vkU0aeskwZ2C+fBLMamHqOqGHm5J7vnEnD+RQzE1yJKXrfsaFdm5z/cak4AGEWlsVaqCR3kYMHFlqmeRqjI9NMi3mfq+yPN9Mg5ucf5DeHszXmtb/NG+Er6tPE9Hw0dzvjedNt8w3XrEybCFZQq+miXcQNRVzy/7Z4+LTgQEs9OaitPWpZyJ9OnfSCiHXpTuhM4J50J4LAlBFuvPByVbvxGrV7/16gaNObDii7c/M6iTRyfGEzkFO7VfBVBpxW8WYOoRHRmesC5Yi7lK3tFO5vz5BrmR9rGYWjZ5BALfAJcb34gENUAYgd7EtZvIvnHDRyJJ0zXeAOEf+PaIpkSPgXRsFveNgMpfK3PjWOk1fNmtSVBNIdGWXbnwIibu4sQa98vh4BJiRmpKqYM=
    username: AgAhOpS2a7PF3Dj8mH1V8CA5g1Ld5QqmzWi7XEYuOemJcrTBq+G6mJFjZ1mzCRK8EDnTIVGSlV636l78MLJNluYn3STClAFbD+hfJosP4/TJPD51d3U4XkrVtRHrq1vDeZuXjf+BY6fyfCh4utdCCisCueSfba1b0MKsCVrxs/XJClUr8mhitqHEsUJbWqhD7alyhlVyJ9xpTadqzwXmjH/Njh8dds0wc41CFZKf7UmchlwjWF2TvTBFP+3xfkWhUiBaNedCgFmBY5O3PSmdNn/hv4bdm9CWJ/nBZDtZGJf4Ix2+3Ssq88Myt0gEA3Z9xPEm/7Osv2nO+Ofowxr4SyrXB5usflI9DY80vnJYNhxuZ8Pxw39wOouQuwyvhGESKYeB6a5QMPjWMumqW1/AgVXdCWawvDYSDrolfVvSd6G7BdGdzpD0BQmLjjAlVvycmF/uB6D/Cj+25Co/fSBtaZtwreoae55WgveR3IRQodGWPzcx6noEddyO+dyvkGa9StlvuiIBikGo0TZX+gpUOXu65pvLwXOhebNlWyzvO/u5ALtnSL0N69e3DyuE7EZ+npCIKr006xEi1Yz5bZKO+kHGhmHKm8GFSqio0lZm+MwoZlOlid7Ok7WTdnOmr3H1TFAfkcZPtSYWhsYZkMpNO56yrArdBq2dOEQqs45lqOPPSyhJX4aGYpiCXAlJvVaPDi3CMRWS
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
