apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: credentials-velero
  namespace: velero
spec:
  encryptedData:
    cloud: AgBi83ELjaPPI0bADqtEdod22P37GVlqs4eViWMZIrUISE7lE0RzDtqcQEO48V+PNWJTSx3PgKvPRXMpYgEJQbA/9OLZQ+PzcxsLzp5XKjecr2Mgio1FtehP9IbDjits3j/ZzHZ8Bzm7/TtkK3wqZ91bvjnaLuYmmneq8jDl7hp6/vC7aroqcqtZ4COSpwRpL7oPBCOYH+Ishe/BRiSeuSgxbuX+jK6Touoen04KksdR9HQkpyEF/sFrNN7QkNOGqb8tr34aIKkoMxGK2nroCt8g674YZrKSC4+GcHhNdjqu6GStlq6NeAufN1pPgGfcHzgiy2IJiVmf9/TWOt9BA2QU0ZfMNvz1ge/ziTypkRK5iwC1WNduOdvi35g3NulYE+WCpYNyx0mYWUJmQfFSWCb6nidLPZJwmfvAesi8dRq6tFFs6lnNoom7hrexvlf9r92bfQCMLncEFXj4SnMlnlaUOKJamcztZwW3rTZn8DLy2yDWd88NC8V+IEQGOjTDSIqEfZzi2hFtBtKKEUeOryJ4TpqkDmMBxQTk17KUWK2VnCECFLSRH0dcAu7ewIwT+y+y9GqFjL2Msk8uKw/tighaMKOOROmZWFxPHa0qRh55dCKfuhBLnTpOxIJ/v4f68KnWP/l37eXztgC6T06uqffxiw+GDGxEPQTE8Zw8u5GRDdiss7+fbZercq7EJ3fsIYWrworNfiCABzX8Ejd2WdaZiBoNlyxVPb64iwV8xuGmAF4zR1FSQnSRHxpdgRhJ4U8IN5bMg3J9/MkWrazVokePD28j3P/aztJhBbRTm5FP0/AodrkB
  template:
    metadata:
      name: credentials-velero
      namespace: velero
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-offsite-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCLZMbcE3y0bZrm7+vl28iFkWvS7ySlfCxWwr9mtbf3+2CyysGvGtuMWmn91ISFlUhh63R03qlaGsurYElVY5EzX/Y3Eri5TkTIG58262T1bOEoAuOmK4TNLwXKdOxcy0r4t8XDL3BTxilyDtnxvuQDcYZ7l5Cg57Mdrc3Gxk9uwEN6EGKRlaJLNTLGglbP9MUWozDR2KPpmf7ibD2KALsRkhXZ8HD1tkLeHChX8Ct3OQGivky7NJNAQiFGe79onDDV3urCHoQLqShSSE7TI1TZNNzzykkr+JcM7nSdedXEYyam1wdJQYjwceIpEu9N9R2IjF/WG8yNxBx9IesxcsovpKvc2xzzvFZz1CDccoIgW8Tp6cxTGNrOnXBmrrvgdLTL6N6aDZzB19Sr1aKrlWlU3Y/0SsLNkSIUOT9Lj1tWRVaF63FNCuNbrr5l+ZThyqSZ5IxzF8BWDfxMf7HxX0bj9yn7eG7EWWLYguPNs2IcYrAPt/0XrEMXLByOd13O6vJKuyFHYHOMryJle1sCKC+Es+MQaRWgkzJrlWIGAzj70wdlTwGldaLhmq6BZSPzb5nu1KrLgEM/079VQER8WiJChYDJO+mNKq706lYAxD00SB8ndHHdsPG1tnJvfG6qp5QzwtEMG0QIoM+8y14ruYuheLDjHutQLVBNGE5Y58Bak69azW5pm6tnk69WFQHwD62REPx8qcyHMrY7AT23Rrt8royc8sHJlQit6uFRfAVy+pi5lN7PvkOGKqcph7GCdZsN6OUgp9NPRU5q35vdTRHAOAZzD2VNCrIoWn5xW5CIfhc1Du5Dcg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-offsite-credentials
      namespace: velero