apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgAcEqEEvM04dQxCta3U8wiUoD1XIvKbXlNzdgQ2zYxNzMm01aNxuaBLxZt12DoviWNAJ0MI8E5DkOIi1cvVfGmEL4FrlwJw8bdejJYhjOb9WS/doGuhCuGIQYY/OK5yVzGZ1vdbnXQ5PXuuuk5iXonHIVuWRri8aunhVMenvs799sE+w8pkwVEI3rsP5X/LjBy+8ASito3F5ixiX/7vSGVkuq2oxzMV7Qu6ngkxzod5g5H0GQAtEclsCB88VGrrdOzK8Y273wAry8C9RoGTrOaAM42bZFBsr32lo0rX22HccEhjH5lEasRHPOKoV/bCVvuQ1eLdbr9BNeEIO5ADaykisFxXpfY5c0ISb9Xfgz/VDFWHOjJF8ajdiXUtin3pPHb1qpX140dRh5YG4tU1a8BEIIbbSOO1WG1QzGHXp7soCU4kpHtMLKEoR3KVrtaaS/eAztOLZBxBK9lMUpHrYiW2MU9Qbju/UsHov2I0zlOW5Xu6MgNhGyuKtkBUMpK4K8CTGgNYqmo4Z6PaXmr051v+Decs9TENSxf6+O5ui8xplQx2Y2A9Cx27lDyo/D6jYlDAXgBgHw1WZ7SGUEyxoGGKtsi8tdfiK5zD/pljIH2jGxmWHBtZ1R8KJ6unbv227mYtZeCWhVKrniHgKgQ7xhb1+OKkk7It9/f0W4PSbw4vpl4fphKAt+b/Y3zDfWCMApdpVRi3Sua70ihceDDcZmZC
  template:
    metadata:
      creationTimestamp: null
      name: velero-repo-credentials
      namespace: velero