apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup
  # Schedule namespace. Must be the namespace of the Velero server. Required.
  namespace: velero
# Parameters about the scheduled backup. Required.
spec:
  # Paused specifies whether the schedule is paused or not
  paused: true
  # SkipImmediately specifies whether to skip backup if schedule is due immediately when unpaused or created.
  # This is a one-time flag that will be automatically reset to false after being consumed.
  # When true, the controller will skip the immediate backup, set LastSkipped timestamp, and reset this to false.
  skipImmediately: false
  # Schedule is a Cron expression defining when to run the Backup
  schedule: 0 1 * * *
  # Specifies whether to use OwnerReferences on backups created by this Schedule.
  # Notice: if set to true, when schedule is deleted, backups will be deleted too. Optional.
  useOwnerReferencesInBackup: false
  # Template is the spec that should be used for each backup triggered by this schedule.
  template:
    resourcePolicy:
      kind: configmap
      name: policy-default
    # CSISnapshotTimeout specifies the time used to wait for
    # CSI VolumeSnapshot status turns to ReadyToUse during creation, before
    # returning error as timeout. The default value is 10 minute.
    csiSnapshotTimeout: 10m
    # Array of namespaces to include in the scheduled backup. If unspecified, all namespaces are included.
    # Optional.
    includedNamespaces:
      - 'calibre'
      - 'gitea'
      - 'nextcloud'
      - 'omada-controller'
      - 'media'
      - 'internal'
    snapshotVolumes: true
    # Where to store the tarball and logs.
    #storageLocation: csi
    # The list of locations in which to store volume snapshots created for backups under this schedule.
    #volumeSnapshotLocations:
    #  - csi
    # whether pod volume file system backup should be used for all volumes by default.
    defaultVolumesToFsBackup: false
    # Whether snapshot data should be moved. If set, data movement is launched after the snapshot is created.
    snapshotMoveData: true
    # The data mover to be used by the backup. If the value is "" or "velero", the built-in data mover will be used.
    datamover: velero
    # UploaderConfig specifies the configuration for the uploader
    uploaderConfig:
      # ParallelFilesUpload is the number of files parallel uploads to perform when using the uploader.
      parallelFilesUpload: 10