apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-encryption-secret
  namespace: velero
spec:
  encryptedData:
    encryptionPassphrase: AgBu2NBB0s76QipO/nCIf+MjfzMmfxW4f75MJtXV6oZMDODDujsezLssL6wislcudFA+ZAlL5gJHxVMbI9KSwL8maOcl96y1a0gkfA19FUD26OcDTgv+61O/wy7DO6WEeZMAN/HjgzMR9bOdo4tfH7cRPm4Ld2HI7hR7LdHBAJ0tpNysQwr5t7GBIhRGHtEXzv7YhHTAIixDoMARMjf9PxZbmnUgpNQ4tT9qio0RRQxMpif6JYPGIlghcrjxm7pOOQfmuJDl0Nb9YWVyyihMV9Pve/W3GVMX4S/sJ3a5TaK93E/JG4gb2+vYSZX4pAl0mg/JcTho3+vT1GGl7MhoHFy7kLNt2yAGln7eEJ+EwYCQa2F+/ElIGTe36f4XSPlrGGBslDObKBJN0W11yukQUV0b0xbpKPA9OS7X5n2BavRqYUHGyyJdlh7zXr0gFUC+DzyxPvQbjlcEVzaOjWBqhC5GKpBamEgdRPvTP0S36jS1kTsIrb4uZfderWHx82wXtHmtLx576r2JHWcIpGxzHdwSDD4175Bg0nsaH+EjH3n0Cmdg/UldCosnvGNN3tmlQe43PkkBv5QioITo4k7RE3RNcd0gMs8kfAC2EDFGuRIpRqsw5PzKJaBnuMX6tvyFFhqGhNLM2ai/JRBLPQWh8hSCi/sluSbi+m6RK0F9zkX281fcdAI3bDyigA+GW5OHHfONpfKsU7uY+2Mky9KP9CslGN6GjQRNiSB7K8HwJ9mxWa3a239ebJPVmMdBMSCEpEyPKA==
  template:
    metadata:
      creationTimestamp: null
      name: storage-encryption-secret
      namespace: velero